/**
 * Created by Tharuka Jayalath on 07/14/2018
 */

module.exports = {
    SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
    SET_USERS: 'SET_USERS',
    SET_ORDERS: 'SET_ORDERS',
    SET_DISPLAY_ORDER_GRID: 'SET_DISPLAY_ORDER_GRID',
    SET_DATE_TIME: 'SET_DATE_TIME',
    SET_ORDER_GRID_DATA: 'SET_ORDER_GRID_DATA',
    SET_USERS_MAP:'SET_USERS_MAP',
    SET_OK: 'SET_OK'

};
